#include <Arduino.h>
#include <Servo.h>

// My plan is to build a solar tracker using 2 servo motors and 6 photoresistors, 2 for each axis. I want to compare the values of the photoresistors and move the servos accordingly.
// In order to achieve good / accurate results, the servos are allowed to move slowly
// The servos are controlled by a PWM signal, which is generated by the ESP32
// The servo's maximum angle is 180 degress

#define SERVO_MIN_ANGLE 0
#define SERVO_MAX_ANGLE 180 

#define SENSOR_AXIS_X1 0
#define SENSOR_AXIS_X2 1
#define SENSOR_AXIS_Y1 2
#define SENSOR_AXIS_Y2 3

#define SERVO_AXIS_X 11
#define SERVO_AXIS_Y 10

Servo servoX;
Servo servoY;

void setup () {
  servoX.attach(SERVO_AXIS_X);
  servoY.attach(SERVO_AXIS_Y);

  Serial.begin(115200);
}

int servoXAngle = 0;
int servoYAngle = 0;

void loop () {
  // Read the values of the photoresistors
  int sensorX1Value = analogRead(SENSOR_AXIS_X1);
  int sensorX2Value = analogRead(SENSOR_AXIS_X2);
  
  int sensorY1Value = analogRead(SENSOR_AXIS_Y1);
  int sensorY2Value = analogRead(SENSOR_AXIS_Y2);

  // Calculate the average value of the photoresistors
  Serial.print("\nX1: ");
  Serial.println(sensorX1Value);
  Serial.print("X2: ");
  Serial.println(sensorX2Value);
  Serial.print("Y1: ");
  Serial.println(sensorY1Value);
  Serial.print("Y2: ");
  Serial.println(sensorY2Value);

  delay(100);
}


//Convert the desired angle to servo angle, 0 = -90
void moveServoX(int angle) {
  int angleOut = 180 - angle;
  servoX.write(angleOut);
}
