#include <Arduino.h>
#include <ESP32Servo.h>

//Altitudes and Azimuths given in the project specifications, 1st value: altitude, 2nd value: azimtuh
int servoCoordinates[6][2] = {{30,70}, {10,0}, {30,40}, {60,70}, {30,100}, {10,140}}; //For azimuth: 0 = -70 in the Project Specifications to give the value directly to the servo; other values adjusted

// The servos are to be moved to the locations given in the project specifications
// The servos are controlled by a PWM signal, which is generated by the ESP32

#define SERVO_AXIS_X 25
#define SERVO_AXIS_Y 26
#define WAIT_TIME    5000  //tbd

Servo servoX;
Servo servoY;

void setup () {
	servoX.attach(SERVO_AXIS_X);
	servoY.attach(SERVO_AXIS_Y);

	servoY.write(0);
	servoX.write(0);
}

void loop () {
	// Move the servos to each of the positions
	for (auto& rows : servoCoordinates) {
    		servoY.write(rows[0]); //Write altitude
    		servoX.write(rows[1]); //Write azimuth
    		delay(WAIT_TIME); //Delay so the servos can move
	}
}